# Generated by Django 3.0.6 on 2020-07-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instigatorID', models.CharField(max_length=120)),
                ('instigatorProductID', models.CharField(max_length=120)),
                ('recieverID', models.CharField(max_length=120)),
                ('recieverProductID', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
