# Generated by Django 3.0.6 on 2020-07-16 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_auto_20200716_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='instigatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instigatorProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='recieverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='recieverProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
