# Generated by Django 3.0.6 on 2020-07-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200716_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='instigatorID',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='recieverID',
        ),
        migrations.AddField(
            model_name='trade',
            name='instigatorUsername',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='recieverUsername',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
