# Generated by Django 3.0.6 on 2020-07-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200716_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
