# Generated by Django 3.0.6 on 2020-07-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_trade_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='traded',
            field=models.BooleanField(default=False),
        ),
    ]
