# Generated by Django 3.0.6 on 2020-07-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
